{% set name = "distilabel" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distilabel-{{ version }}.tar.gz
  sha256: 9f6c0ebce54bd1a62ab4e500b4d5ce4da60dc43ae678667176ad58ec80269911

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - datasets >=2.14.0
    - jinja2 >=3.1.2
    - rich >=13.5.0
    - tenacity >=8
    - importlib-resources >=6.1.1
    - multiprocess

test:
  imports:
    - distilabel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.argilla.io/
  summary: AI Feedback (AIF) framework
  dev_url: https://github.com/argilla/distilabel
  license: Apache-2.0
  license_file: LICENSE
  description: |
    
    PyPI: [https://pypi.org/project/{{ name|lower }}/](https://pypi.org/project/{{ name|lower }}/)

    ---
    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).
  
  dev_url: https://github.com/argilla-io/distilabel
  doc_url: https://distilabel.argilla.io/

extra:
  recipe-maintainers:
    - sugatoray
